import { useAppData } from './useAppData'
import type { Appointment } from '@/types/database'

const sampleAppointments: Appointment[] = [
  {
    id: '1',
    parent_id: 'mother',
    doctor_name: 'Dr. Carlos Mendes',
    specialty: 'Cardiologia',
    location: 'Hospital Sírio-Libanês - Av. Paulista',
    date: '2026-07-05',
    time: '09:30',
    type: 'consulta',
    status: 'confirmed',
    notes: 'Trazer exames anteriores e carteirinha do plano',
    reminder_days: 1,
    created_by: 'João',
    created_at: '2026-06-15T10:00:00Z',
    updated_at: '2026-06-15T10:00:00Z',
  },
  {
    id: '2',
    parent_id: 'father',
    doctor_name: 'Dra. Ana Paula Rocha',
    specialty: 'Ortopedia',
    location: 'Clínica São Paulo - Rua Augusta',
    date: '2026-07-10',
    time: '14:00',
    type: 'retorno',
    status: 'scheduled',
    notes: 'Revisão pós-cirurgia do joelho',
    reminder_days: 2,
    created_by: 'Maria',
    created_at: '2026-06-20T14:00:00Z',
    updated_at: '2026-06-20T14:00:00Z',
  },
  {
    id: '3',
    parent_id: 'both',
    doctor_name: 'Laboratório Fleury',
    specialty: 'Exames Laboratoriais',
    location: 'Unidade Pinheiros - Av. Rebouças',
    date: '2026-07-03',
    time: '07:00',
    type: 'exame',
    status: 'confirmed',
    notes: 'Jejum de 12h obrigatório. Hemograma completo, glicose, colesterol.',
    reminder_days: 1,
    created_by: 'Pedro',
    created_at: '2026-06-25T09:00:00Z',
    updated_at: '2026-06-25T09:00:00Z',
  },
  {
    id: '4',
    parent_id: 'mother',
    doctor_name: 'Dra. Fernanda Lima',
    specialty: 'Endocrinologia',
    location: 'Hospital Albert Einstein - Morumbi',
    date: '2026-06-28',
    time: '11:00',
    type: 'consulta',
    status: 'completed',
    notes: 'Ajuste de medicação para diabetes. Nova receita emitida.',
    reminder_days: 1,
    created_by: 'João',
    created_at: '2026-06-10T08:00:00Z',
    updated_at: '2026-06-28T12:00:00Z',
  },
]

export function useAppointments() {
  return useAppData<Appointment>({ key: 'appointments', initialData: sampleAppointments })
}
