import { useAppData } from './useAppData'
import type { Document } from '@/types/database'

const sampleDocuments: Document[] = [
  {
    id: '1',
    file_name: 'Carteirinha_Plano_Saude_Mae.pdf',
    file_type: 'pdf',
    file_size: 1024 * 1024,
    file_url: '#',
    category: 'plano-saude',
    parent_id: 'mother',
    expiry_date: '2026-12-31',
    description: 'Carteirinha do plano de saúde da mãe - válida até dezembro',
    uploaded_by: 'João',
    uploaded_at: '2026-01-10T10:00:00Z',
  },
  {
    id: '2',
    file_name: 'Receita_Metformina_Dra_Fernanda.pdf',
    file_type: 'pdf',
    file_size: 512 * 1024,
    file_url: '#',
    category: 'receitas',
    parent_id: 'mother',
    expiry_date: '2026-09-15',
    description: 'Receita de metformina renovada em junho',
    uploaded_by: 'Maria',
    uploaded_at: '2026-06-28T14:00:00Z',
  },
  {
    id: '3',
    file_name: 'Exame_Sangue_Junho_2026.pdf',
    file_type: 'pdf',
    file_size: 2048 * 1024,
    file_url: '#',
    category: 'exames',
    parent_id: 'general',
    expiry_date: null,
    description: 'Resultados dos exames de sangue de junho 2026',
    uploaded_by: 'Pedro',
    uploaded_at: '2026-06-25T09:00:00Z',
  },
  {
    id: '4',
    file_name: 'RG_Pai.jpg',
    file_type: 'image',
    file_size: 3072 * 1024,
    file_url: '#',
    category: 'pessoais',
    parent_id: 'father',
    expiry_date: null,
    description: 'RG do pai - cópia digital',
    uploaded_by: 'João',
    uploaded_at: '2025-03-15T11:00:00Z',
  },
  {
    id: '5',
    file_name: 'Testamento.pdf',
    file_type: 'pdf',
    file_size: 4096 * 1024,
    file_url: '#',
    category: 'legais',
    parent_id: 'general',
    expiry_date: null,
    description: 'Testamento atualizado 2025',
    uploaded_by: 'João',
    uploaded_at: '2025-06-20T16:00:00Z',
  },
  {
    id: '6',
    file_name: 'Carteirinha_Plano_Saude_Pai.pdf',
    file_type: 'pdf',
    file_size: 1024 * 1024,
    file_url: '#',
    category: 'plano-saude',
    parent_id: 'father',
    expiry_date: '2026-12-31',
    description: 'Carteirinha do plano de saúde do pai',
    uploaded_by: 'Maria',
    uploaded_at: '2026-01-10T10:30:00Z',
  },
]

export function useDocuments() {
  return useAppData<Document>({ key: 'documents', initialData: sampleDocuments })
}
