import { useAppData } from './useAppData'
import type { PriceQuote } from '@/types/database'

const sampleQuotes: PriceQuote[] = [
  {
    id: '1',
    item_name: 'Metformina 500mg (30 comp)',
    category: 'remedio',
    store_name: 'Drogaria São Paulo',
    price: 28.5,
    quantity: 1,
    unit: 'caixa',
    status: 'aprovado',
    notes: 'Melhor preço encontrado, comprar mensalmente',
    date: '2026-06-25',
    created_by: 'João',
    created_at: '2026-06-25T10:00:00Z',
  },
  {
    id: '2',
    item_name: 'Losartana 50mg (30 comp)',
    category: 'remedio',
    store_name: 'Pague Menos',
    price: 22.9,
    quantity: 2,
    unit: 'caixa',
    status: 'pendente',
    notes: 'Preço promocional, vale a pena comprar 2 caixas',
    date: '2026-06-27',
    created_by: 'Maria',
    created_at: '2026-06-27T14:00:00Z',
  },
  {
    id: '3',
    item_name: 'Cadeira de Rodas Premium',
    category: 'equipamento-medico',
    store_name: 'Orthofran',
    price: 1250.0,
    quantity: 1,
    unit: 'un',
    status: 'pendente',
    notes: 'Cotação para emergência. Pai está com dificuldade para longas caminhadas.',
    date: '2026-06-20',
    created_by: 'Pedro',
    created_at: '2026-06-20T16:00:00Z',
  },
  {
    id: '4',
    item_name: 'Fralda Geriátrica M (8 un)',
    category: 'fralda',
    store_name: 'Mercado Livre',
    price: 34.9,
    quantity: 5,
    unit: 'pacote',
    status: 'aprovado',
    notes: 'Comprar em quantidade para ter estoque',
    date: '2026-06-26',
    created_by: 'João',
    created_at: '2026-06-26T09:00:00Z',
  },
  {
    id: '5',
    item_name: 'Fisioterapia Domiciliar',
    category: 'servico',
    store_name: 'Clínica Reabilitar',
    price: 180.0,
    quantity: 8,
    unit: 'sessão',
    status: 'pendente',
    notes: 'Pacote de 8 sessões. Precisamos decidir juntos.',
    date: '2026-06-28',
    created_by: 'Maria',
    created_at: '2026-06-28T11:00:00Z',
  },
]

export function useQuotes() {
  return useAppData<PriceQuote>({ key: 'price_quotes', initialData: sampleQuotes })
}
